version: "3.9"

services:
  api:
    image: notes-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings:Database: "Server=db;Database=NotesDatabase;User=NotesUser;Password=NotesPassword;MultipleActiveResultSets=true"
    ports:
      - "9411:80"
    restart: always
    depends_on:
      - db
    healthcheck:
      test: wget --no-verbose http://localhost:80/healthcheck || exit 1
      interval: 10s
      timeout: 3s
      retries: 600
      start_period: 10s
  db:
    image: mssql
    volumes:
      - mssqldata-notes:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SAPassword123"
      DATABASE: "NotesDatabase"
      USER: "NotesUser"
      PASSWORD: "NotesPassword"
    ports:
      - "9101:1433"
    restart: always
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -b -S localhost -U sa -P "SAPassword123" -Q "SELECT * FROM [NotesDatabase].[INFORMATION_SCHEMA].[TABLES]" || exit 1
      interval: 10s
      timeout: 3s
      retries: 600
      start_period: 10s

volumes:
  mssqldata-notes: