version: "3.9"

services:
  web:
    image: notes-web
    environment:
      API_URL: "http://api:9410/notes"
    ports:
      - "9510:80"
    restart: always
    build:
        context: NotesWeb
  api:
    image: notes-api
    environment:
      ConnectionStrings:Database: "Server=db;Database=$DATABASE_NAME;User=$DATABASE_USER;Password=$DATABASE_PASSWORD;MultipleActiveResultSets=true"
    ports:
      - "9410:80"
    restart: always
    healthcheck:
      test: wget --no-verbose http://localhost:80/healthcheck || exit 1
      interval: 10s
      timeout: 3s
      retries: 600
      start_period: 10s
    build:
      context: NotesApi
  db:
    image: mssql
    volumes:
      - mssqldata:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: $DATABASE_SA_PASSWORD
      DATABASE: $DATABASE_NAME
      USER: $DATABASE_USER
      PASSWORD: $DATABASE_PASSWORD
    ports:
      - "9101:1433"
    restart: always
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -b -S localhost -U sa -P $DATABASE_SA_PASSWORD -Q "SELECT * FROM [$DATABASE_NAME].[INFORMATION_SCHEMA].[TABLES]" || exit 1
      interval: 10s
      timeout: 3s
      retries: 600
      start_period: 10s
    build:
      context: database-setup

volumes:
  mssqldata: